export {default as Header} from './Header.js'
export {default as Footer} from './Footer.js'
export {default as Body} from './Body.js'
export {default as Demo} from './Demo/Demo.js'
export {default as Logo} from './Logo.js'
export {default as PageHeading} from './PageHeading.js'
export {default as PageContent} from './PageContent.js'
